declare namespace NodeJS {
  interface ProcessEnv {
    EXPO_PUBLIC_APP_CHANNEL?: string;
    EXPO_PUBLIC_ORGANIZER_TEST_MODE?: string;
    EXPO_PUBLIC_ORGANIZER_SECURITY_ENFORCED?: string;
    EXPO_PUBLIC_PARTICIPANT_SECURITY_ENFORCED?: string;
    EXPO_PUBLIC_DEMO_ALL_OPEN?: string;
    EXPO_PUBLIC_ADMOB_ENABLED?: string;
    EXPO_PUBLIC_ADMOB_TEST_MODE?: string;
    EXPO_PUBLIC_PAID_FEATURE_UNLOCK_CONTACT?: string;
    EXPO_PUBLIC_ADMIN_CONTACT_EMAIL?: string;
    EXPO_PUBLIC_EMAIL_WEBHOOK_URL?: string;
    EXPO_PUBLIC_ORGANIZER_COMPLIANCE_WEBHOOK_URL?: string;
    EXPO_PUBLIC_EVENT_WEB_BASE_URL?: string;
    EXPO_PUBLIC_PRIVACY_POLICY_URL?: string;
    EXPO_PUBLIC_SUPABASE_URL?: string;
    EXPO_PUBLIC_SUPABASE_ANON_KEY?: string;
    EXPO_PUBLIC_SPONSOR_CHECKOUT_URL?: string;
    EXPO_PUBLIC_SPONSOR_MODULE_CHECKOUT_URL?: string;
    EXPO_PUBLIC_STRIPE_CONNECT_URL?: string;
    EXPO_PUBLIC_STRIPE_CONNECT_SYNC_URL?: string;
    EXPO_PUBLIC_PARTICIPANT_CHECKOUT_URL?: string;
    EXPO_PUBLIC_ADMOB_BANNER_UNIT_ID_ANDROID?: string;
    EXPO_PUBLIC_ADMOB_BANNER_UNIT_ID_IOS?: string;
    EXPO_PUBLIC_ADMOB_INTERSTITIAL_UNIT_ID_ANDROID?: string;
    EXPO_PUBLIC_ADMOB_INTERSTITIAL_UNIT_ID_IOS?: string;
  }
}
