import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: '#04192E',
  },
  loadingSafeArea: {
    flex: 1,
    backgroundColor: '#04192E',
    alignItems: 'center',
    justifyContent: 'center',
  },
  loadingContainer: {
    alignItems: 'center',
    justifyContent: 'center',
  },
  loadingTitle: {
    color: '#F1F6FA',
    fontSize: 26,
    fontWeight: '800',
  },
  loadingText: {
    marginTop: 8,
    color: '#C4D8E8',
    fontSize: 14,
  },
  gradient: {
    flex: 1,
  },
  headerRow: {
    paddingHorizontal: 16,
    paddingVertical: 14,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    borderBottomWidth: 1,
    borderBottomColor: 'rgba(255,255,255,0.12)',
  },
  appTitle: {
    color: '#F7FBFF',
    fontSize: 22,
    fontWeight: '900',
  },
  appSubtitle: {
    color: '#B7D2E8',
    fontSize: 12,
    marginTop: 2,
  },
  headerAction: {
    backgroundColor: '#F1C65C',
    paddingHorizontal: 14,
    paddingVertical: 8,
    borderRadius: 14,
  },
  headerActionText: {
    color: '#032035',
    fontWeight: '800',
    fontSize: 13,
  },
  screenWrapper: {
    flex: 1,
  },
  scrollContent: {
    paddingHorizontal: 14,
    paddingTop: 12,
    paddingBottom: 120,
    gap: 12,
  },
  card: {
    borderRadius: 18,
    backgroundColor: 'rgba(8, 30, 47, 0.92)',
    borderWidth: 1,
    borderColor: 'rgba(151, 204, 225, 0.26)',
    padding: 14,
    gap: 10,
  },
  cardTitle: {
    color: '#F5FAFF',
    fontSize: 18,
    fontWeight: '800',
  },
  cardParagraph: {
    color: '#C3DAEA',
    fontSize: 14,
    lineHeight: 20,
  },
  fieldBlock: {
    gap: 6,
  },
  fieldLabel: {
    color: '#D6E8F4',
    fontWeight: '700',
    fontSize: 13,
  },
  input: {
    backgroundColor: 'rgba(248, 252, 255, 0.97)',
    color: '#06253E',
    borderRadius: 12,
    borderWidth: 1,
    borderColor: '#B8D3E6',
    paddingHorizontal: 12,
    paddingVertical: 10,
    fontSize: 15,
  },
  inputMultiline: {
    minHeight: 90,
  },
  switchBlock: {
    gap: 6,
  },
  switchHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 10,
  },
  helperText: {
    color: '#9DC2D8',
    fontSize: 12,
    lineHeight: 17,
  },
  primaryButton: {
    backgroundColor: '#2DBCA4',
    borderRadius: 12,
    paddingVertical: 12,
    alignItems: 'center',
    justifyContent: 'center',
  },
  primaryButtonCompact: {
    marginTop: 8,
    backgroundColor: '#2DBCA4',
    borderRadius: 10,
    paddingVertical: 10,
    alignItems: 'center',
  },
  primaryButtonText: {
    color: '#032033',
    fontWeight: '900',
    fontSize: 14,
  },
  secondaryButton: {
    backgroundColor: 'transparent',
    borderColor: '#95BBD5',
    borderWidth: 1,
    borderRadius: 12,
    paddingVertical: 10,
    alignItems: 'center',
    justifyContent: 'center',
  },
  secondaryButtonText: {
    color: '#D7EAF7',
    fontWeight: '700',
    fontSize: 14,
  },
  inlineMetricRow: {
    flexDirection: 'row',
    gap: 8,
    flexWrap: 'wrap',
  },
  homeTopActions: {
    flexDirection: 'row',
    justifyContent: 'flex-start',
  },
  languageRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 10,
  },
  languageSwitchWrap: {
    flexDirection: 'row',
    gap: 8,
  },
  languageChip: {
    borderWidth: 1,
    borderColor: '#7DA8C2',
    borderRadius: 999,
    paddingHorizontal: 12,
    paddingVertical: 7,
    backgroundColor: 'transparent',
  },
  languageChipActive: {
    backgroundColor: '#F1C65C',
    borderColor: '#F1C65C',
  },
  languageChipText: {
    color: '#D8EAF6',
    fontWeight: '700',
    fontSize: 12,
  },
  languageChipTextActive: {
    color: '#022033',
  },
  metricChip: {
    backgroundColor: 'rgba(19, 62, 90, 0.88)',
    borderRadius: 12,
    paddingVertical: 10,
    paddingHorizontal: 12,
    borderWidth: 1,
    borderColor: 'rgba(120, 177, 205, 0.6)',
    minWidth: 130,
  },
  metricValue: {
    color: '#F1C65C',
    fontSize: 18,
    fontWeight: '900',
  },
  metricLabel: {
    color: '#BFD9EA',
    fontSize: 12,
    marginTop: 2,
  },
  listCard: {
    backgroundColor: 'rgba(11, 38, 58, 0.96)',
    borderRadius: 12,
    borderWidth: 1,
    borderColor: 'rgba(146, 192, 215, 0.42)',
    padding: 10,
    gap: 4,
  },
  listCardSelected: {
    borderColor: '#F1C65C',
    borderWidth: 1.6,
  },
  listTitle: {
    color: '#F7FAFD',
    fontWeight: '800',
    fontSize: 15,
  },
  listSubText: {
    color: '#BCD5E8',
    fontSize: 12,
    lineHeight: 17,
  },
  inlineActionRow: {
    flexDirection: 'row',
    gap: 8,
    marginTop: 8,
  },
  inlineActionButton: {
    backgroundColor: '#1F88AA',
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 10,
  },
  inlineActionButtonText: {
    color: '#EAF5FD',
    fontSize: 12,
    fontWeight: '700',
  },
  registrationCard: {
    backgroundColor: 'rgba(8, 30, 47, 0.95)',
    borderRadius: 10,
    borderWidth: 1,
    borderColor: 'rgba(117, 176, 204, 0.45)',
    padding: 10,
    gap: 3,
  },
  methodRow: {
    flexDirection: 'row',
    gap: 8,
    flexWrap: 'wrap',
  },
  methodChip: {
    borderWidth: 1,
    borderColor: '#7DA8C2',
    borderRadius: 999,
    paddingHorizontal: 12,
    paddingVertical: 7,
  },
  methodChipActive: {
    backgroundColor: '#F1C65C',
    borderColor: '#F1C65C',
  },
  methodChipText: {
    color: '#D8EAF6',
    fontWeight: '700',
    fontSize: 12,
  },
  methodChipTextActive: {
    color: '#022033',
  },
  checkboxRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    marginTop: 4,
  },
  checkbox: {
    width: 22,
    height: 22,
    borderRadius: 6,
    borderWidth: 1,
    borderColor: '#8CB4CD',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'rgba(255,255,255,0.05)',
  },
  checkboxActive: {
    backgroundColor: '#2DBCA4',
    borderColor: '#2DBCA4',
  },
  checkboxMark: {
    color: '#032031',
    fontSize: 12,
    fontWeight: '900',
  },
  checkboxLabel: {
    color: '#D0E5F4',
    fontSize: 13,
    flex: 1,
    lineHeight: 18,
  },
  blockSpacing: {
    gap: 8,
  },
  fallbackContainer: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 24,
    gap: 16,
  },
  fallbackText: {
    color: '#D4E8F6',
    fontSize: 15,
    textAlign: 'center',
    lineHeight: 22,
  },
  bannerWrap: {
    position: 'absolute',
    left: 14,
    right: 14,
    bottom: 18,
    paddingHorizontal: 14,
    paddingVertical: 12,
    borderRadius: 14,
    backgroundColor: '#F1C65C',
    borderWidth: 1,
    borderColor: '#FFE39D',
  },
  bannerText: {
    color: '#2D2001',
    fontWeight: '800',
    fontSize: 13,
    textAlign: 'center',
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(4, 16, 28, 0.82)',
    justifyContent: 'center',
    paddingHorizontal: 14,
  },
  legalModalCard: {
    maxHeight: '85%',
    borderRadius: 16,
    backgroundColor: '#08243C',
    borderWidth: 1,
    borderColor: '#7DA8C2',
    padding: 14,
    gap: 12,
  },
  legalModalContent: {
    gap: 10,
  },
  modalTitle: {
    color: '#F5FAFF',
    fontSize: 20,
    fontWeight: '900',
    marginBottom: 4,
  },
  modalParagraph: {
    color: '#C4DBED',
    fontSize: 13,
    lineHeight: 19,
  },
  interstitialCard: {
    borderRadius: 16,
    backgroundColor: '#0A2A45',
    borderWidth: 1,
    borderColor: '#96BCD5',
    padding: 18,
    alignItems: 'center',
    gap: 10,
  },
  interstitialTitle: {
    color: '#F7FBFF',
    fontSize: 20,
    fontWeight: '900',
  },
  interstitialText: {
    color: '#D2E7F6',
    fontSize: 14,
    textAlign: 'center',
  },
  interstitialSponsor: {
    color: '#F1C65C',
    fontSize: 13,
    textAlign: 'center',
    fontWeight: '700',
  },
});
