import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: '#030E1A',
    overflow: 'hidden',
  },
  loadingSafeArea: {
    flex: 1,
    backgroundColor: '#030E1A',
    alignItems: 'center',
    justifyContent: 'center',
  },
  loadingContainer: {
    alignItems: 'center',
    justifyContent: 'center',
  },
  loadingTitle: {
    color: '#F4FBFF',
    fontSize: 26,
    fontWeight: '800',
    letterSpacing: 0.2,
  },
  loadingText: {
    marginTop: 8,
    color: '#A6C5D8',
    fontSize: 14,
  },
  gradient: {
    flex: 1,
    overflow: 'hidden',
  },
  backgroundDecor: {
    position: 'absolute',
    top: 0,
    right: 0,
    bottom: 0,
    left: 0,
  },
  backgroundOrb: {
    position: 'absolute',
    width: 380,
    height: 380,
    borderRadius: 999,
    backgroundColor: 'rgba(56, 220, 205, 0.13)',
  },
  backgroundOrbTop: {
    top: -140,
    right: -90,
  },
  backgroundOrbBottom: {
    bottom: -150,
    left: -110,
    backgroundColor: 'rgba(29, 153, 225, 0.14)',
  },
  headerShell: {
    width: '100%',
    borderBottomWidth: 1,
    borderBottomColor: 'rgba(154, 220, 244, 0.2)',
    backgroundColor: 'rgba(5, 20, 37, 0.5)',
  },
  headerRow: {
    width: '100%',
    maxWidth: 1200,
    alignSelf: 'center',
    paddingHorizontal: 16,
    paddingVertical: 15,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  headerRowDesktop: {
    paddingHorizontal: 24,
    paddingVertical: 19,
  },
  appTitle: {
    color: '#F7FDFF',
    fontSize: 23,
    fontWeight: '900',
    letterSpacing: 0.3,
  },
  appSubtitle: {
    color: '#A9C8DB',
    fontSize: 12,
    marginTop: 4,
    letterSpacing: 0.15,
  },
  headerAction: {
    backgroundColor: '#F1C65C',
    paddingHorizontal: 14,
    paddingVertical: 8,
    borderRadius: 14,
  },
  headerActionText: {
    color: '#032035',
    fontWeight: '800',
    fontSize: 13,
  },
  screenWrapper: {
    flex: 1,
    width: '100%',
  },
  screenWrapperDesktop: {
    paddingHorizontal: 8,
  },
  scrollContent: {
    width: '100%',
    maxWidth: 1200,
    alignSelf: 'center',
    minWidth: 0,
    paddingHorizontal: 18,
    paddingTop: 18,
    paddingBottom: 124,
    gap: 16,
  },
  screenSplit: {
    gap: 16,
  },
  screenSplitDesktop: {
    flexDirection: 'row',
    alignItems: 'flex-start',
  },
  screenSplitColumn: {
    gap: 16,
    minWidth: 0,
  },
  screenSplitColumnMain: {
    flex: 1.15,
    minWidth: 0,
  },
  screenSplitColumnSide: {
    flex: 0.85,
    minWidth: 0,
  },
  card: {
    borderRadius: 20,
    backgroundColor: 'rgba(8, 27, 46, 0.84)',
    borderWidth: 1,
    borderColor: 'rgba(114, 193, 223, 0.34)',
    padding: 16,
    gap: 11,
    minWidth: 0,
    shadowColor: '#020A12',
    shadowOffset: { width: 0, height: 14 },
    shadowOpacity: 0.34,
    shadowRadius: 20,
    elevation: 8,
  },
  cardTitle: {
    color: '#ECFAFF',
    fontSize: 20,
    fontWeight: '800',
    letterSpacing: 0.2,
  },
  cardParagraph: {
    color: '#C2DDF0',
    fontSize: 14.5,
    lineHeight: 21,
  },
  fieldBlock: {
    gap: 6,
  },
  fieldLabel: {
    color: '#D8EDF8',
    fontWeight: '700',
    fontSize: 13.5,
    flexShrink: 1,
  },
  input: {
    backgroundColor: 'rgba(7, 34, 54, 0.86)',
    color: '#E8F6FF',
    borderRadius: 13,
    borderWidth: 1,
    borderColor: 'rgba(122, 182, 210, 0.6)',
    paddingHorizontal: 13,
    paddingVertical: 11,
    fontSize: 15,
  },
  inputMultiline: {
    minHeight: 90,
  },
  switchBlock: {
    gap: 6,
  },
  switchHeader: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    justifyContent: 'space-between',
    gap: 10,
    flexWrap: 'wrap',
  },
  helperText: {
    color: '#9FC6DD',
    fontSize: 12,
    lineHeight: 17,
    flexShrink: 1,
  },
  sectionDivider: {
    height: 1,
    backgroundColor: 'rgba(146, 201, 228, 0.35)',
    marginVertical: 2,
  },
  noticeCard: {
    borderRadius: 12,
    borderWidth: 1,
    padding: 12,
    gap: 4,
    minWidth: 0,
  },
  noticeCardError: {
    backgroundColor: 'rgba(93, 33, 33, 0.85)',
    borderColor: 'rgba(244, 120, 120, 0.6)',
  },
  noticeCardSuccess: {
    backgroundColor: 'rgba(17, 75, 64, 0.85)',
    borderColor: 'rgba(83, 227, 203, 0.6)',
  },
  noticeCardInfo: {
    backgroundColor: 'rgba(7, 30, 49, 0.85)',
    borderColor: 'rgba(118, 180, 209, 0.55)',
  },
  noticeTitle: {
    color: '#F1FAFF',
    fontWeight: '800',
    fontSize: 13,
  },
  noticeText: {
    color: '#DCEFFB',
    fontSize: 12,
    lineHeight: 17,
  },
  primaryButton: {
    backgroundColor: '#36D4B8',
    borderRadius: 13,
    borderWidth: 1,
    borderColor: '#8AF7E4',
    paddingVertical: 12.5,
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: '#0A2A33',
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.28,
    shadowRadius: 12,
    elevation: 5,
  },
  primaryButtonCompact: {
    marginTop: 10,
    backgroundColor: '#36D4B8',
    borderRadius: 11,
    borderWidth: 1,
    borderColor: '#8AF7E4',
    paddingVertical: 10.5,
    alignItems: 'center',
  },
  primaryButtonText: {
    color: '#022637',
    fontWeight: '900',
    fontSize: 14.5,
    letterSpacing: 0.2,
    textAlign: 'center',
  },
  secondaryButton: {
    backgroundColor: 'rgba(7, 31, 49, 0.55)',
    borderColor: 'rgba(150, 198, 223, 0.65)',
    borderWidth: 1,
    borderRadius: 12,
    paddingVertical: 10.5,
    alignItems: 'center',
    justifyContent: 'center',
  },
  secondaryButtonText: {
    color: '#DCEFFB',
    fontWeight: '700',
    fontSize: 14,
    textAlign: 'center',
  },
  inlineMetricRow: {
    flexDirection: 'row',
    gap: 8,
    flexWrap: 'wrap',
  },
  homeTopActions: {
    flexDirection: 'row',
    justifyContent: 'flex-start',
    flexWrap: 'wrap',
    gap: 8,
  },
  languageRow: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    justifyContent: 'flex-start',
    flexWrap: 'wrap',
    gap: 10,
  },
  languageSwitchWrap: {
    flexDirection: 'row',
    gap: 8,
    flexWrap: 'wrap',
  },
  languageChip: {
    borderWidth: 1,
    borderColor: '#79ACC7',
    borderRadius: 999,
    paddingHorizontal: 12,
    paddingVertical: 8,
    backgroundColor: 'rgba(8, 33, 52, 0.54)',
  },
  languageChipActive: {
    backgroundColor: '#36D4B8',
    borderColor: '#7EEFD9',
  },
  languageChipText: {
    color: '#D8EDF8',
    fontWeight: '700',
    fontSize: 12,
  },
  languageChipTextActive: {
    color: '#032736',
  },
  metricChip: {
    backgroundColor: 'rgba(13, 50, 75, 0.86)',
    borderRadius: 13,
    paddingVertical: 10,
    paddingHorizontal: 12,
    borderWidth: 1,
    borderColor: 'rgba(123, 190, 221, 0.56)',
    minWidth: 130,
  },
  metricValue: {
    color: '#89F6E2',
    fontSize: 18,
    fontWeight: '900',
  },
  metricLabel: {
    color: '#BFDCED',
    fontSize: 12,
    marginTop: 2,
  },
  listCard: {
    backgroundColor: 'rgba(11, 39, 60, 0.9)',
    borderRadius: 14,
    borderWidth: 1,
    borderColor: 'rgba(141, 201, 228, 0.42)',
    padding: 12,
    gap: 6,
    minWidth: 0,
  },
  listCardSelected: {
    borderColor: '#53E3CB',
    borderWidth: 1.8,
  },
  listTitle: {
    color: '#F1FAFF',
    fontWeight: '800',
    fontSize: 15,
    flexShrink: 1,
  },
  listSubText: {
    color: '#BBD9EB',
    fontSize: 12,
    lineHeight: 17,
    flexShrink: 1,
  },
  inlineActionRow: {
    flexDirection: 'row',
    gap: 8,
    marginTop: 8,
    flexWrap: 'wrap',
  },
  suggestionButtonRow: {
    flexDirection: 'row',
    gap: 8,
    flexWrap: 'wrap',
  },
  suggestionButton: {
    flexGrow: 1,
    minWidth: 170,
  },
  inlineActionButton: {
    backgroundColor: '#1C86AB',
    paddingHorizontal: 12,
    paddingVertical: 8.5,
    borderRadius: 10,
    minWidth: 0,
    flexShrink: 1,
    maxWidth: '100%',
  },
  inlineActionButtonText: {
    color: '#EAF5FD',
    fontSize: 12.5,
    fontWeight: '700',
    textAlign: 'center',
  },
  registrationCard: {
    backgroundColor: 'rgba(7, 30, 49, 0.89)',
    borderRadius: 12,
    borderWidth: 1,
    borderColor: 'rgba(118, 180, 209, 0.48)',
    padding: 12,
    gap: 4,
    minWidth: 0,
  },
  sponsorLogoPreview: {
    width: '100%',
    height: 140,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: 'rgba(118, 180, 209, 0.48)',
    backgroundColor: 'rgba(7, 30, 49, 0.89)',
    resizeMode: 'cover',
  },
  qrCodePreviewImage: {
    width: 180,
    height: 180,
    alignSelf: 'center',
    borderRadius: 12,
    borderWidth: 1,
    borderColor: 'rgba(118, 180, 209, 0.48)',
    backgroundColor: '#FFFFFF',
    resizeMode: 'contain',
  },
  methodRow: {
    flexDirection: 'row',
    gap: 8,
    flexWrap: 'wrap',
  },
  methodChip: {
    borderWidth: 1,
    borderColor: '#7DAEC9',
    borderRadius: 999,
    paddingHorizontal: 12,
    paddingVertical: 7,
    backgroundColor: 'rgba(7, 32, 50, 0.5)',
    maxWidth: '100%',
  },
  methodChipActive: {
    backgroundColor: '#36D4B8',
    borderColor: '#7EEFD9',
  },
  methodChipText: {
    color: '#D8EDF8',
    fontWeight: '700',
    fontSize: 12,
  },
  methodChipTextActive: {
    color: '#022637',
  },
  checkboxRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    marginTop: 4,
  },
  checkbox: {
    width: 22,
    height: 22,
    borderRadius: 6,
    borderWidth: 1,
    borderColor: '#91BCD5',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'rgba(255,255,255,0.08)',
  },
  checkboxActive: {
    backgroundColor: '#36D4B8',
    borderColor: '#7EEFD9',
  },
  checkboxMark: {
    color: '#032636',
    fontSize: 12,
    fontWeight: '900',
  },
  checkboxLabel: {
    color: '#D4EAF8',
    fontSize: 13,
    flex: 1,
    lineHeight: 18,
  },
  blockSpacing: {
    gap: 8,
  },
  fallbackContainer: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 24,
    gap: 16,
  },
  fallbackText: {
    color: '#D9EDFA',
    fontSize: 15,
    textAlign: 'center',
    lineHeight: 22,
  },
  bannerWrap: {
    position: 'absolute',
    alignSelf: 'center',
    bottom: 18,
    paddingHorizontal: 15,
    paddingVertical: 12,
    borderRadius: 14,
    backgroundColor: '#E8BC52',
    borderWidth: 1,
    borderColor: '#FDE4A6',
    shadowColor: '#251300',
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.26,
    shadowRadius: 14,
    elevation: 4,
  },
  adBannerWrap: {
    position: 'absolute',
    alignSelf: 'center',
    bottom: 18,
    alignItems: 'center',
    justifyContent: 'center',
  },
  bannerText: {
    color: '#312202',
    fontWeight: '800',
    fontSize: 13,
    textAlign: 'center',
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(3, 12, 22, 0.86)',
    justifyContent: 'center',
    paddingHorizontal: 14,
  },
  legalModalCard: {
    maxHeight: '85%',
    borderRadius: 18,
    backgroundColor: '#09233A',
    borderWidth: 1,
    borderColor: 'rgba(131, 183, 210, 0.72)',
    padding: 14,
    gap: 12,
  },
  legalModalContent: {
    gap: 10,
  },
  modalTitle: {
    color: '#EEF9FF',
    fontSize: 20,
    fontWeight: '900',
    marginBottom: 4,
  },
  modalParagraph: {
    color: '#C6DEEF',
    fontSize: 13,
    lineHeight: 19,
  },
  interstitialCard: {
    borderRadius: 18,
    backgroundColor: '#0A2741',
    borderWidth: 1,
    borderColor: 'rgba(145, 200, 228, 0.72)',
    padding: 18,
    alignItems: 'center',
    gap: 10,
  },
  interstitialTitle: {
    color: '#F2FAFF',
    fontSize: 20,
    fontWeight: '900',
  },
  interstitialText: {
    color: '#D5EAF8',
    fontSize: 14,
    textAlign: 'center',
  },
  interstitialSponsor: {
    color: '#86F6E1',
    fontSize: 13,
    textAlign: 'center',
    fontWeight: '700',
  },
});
